---
name: "pre-release"

on:
  push:
    branches:
      - "main"
    paths:
      - 'companion/**'

jobs:
  pre-release:
    runs-on: windows-latest
    steps:

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.x
          
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - uses: actions/cache@v4
        with:
          path: |
            %LocalAppData%\go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Build
        run: cd companion && go generate ./... && go build -ldflags -H=windowsgui -o ../companion.exe ./cmd/companion
        
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            companion.exe
